import { describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import {
  parseVersionFromEnv,
  validateSemver,
  syncVersion,
  checkVersion,
  type TargetResult,
} from "./sync-version";

describe("Version validation and parsing", () => {
  it("parses valid QURIODB_VERSION from env string", () => {
    const envContent = "FOO=bar\nQURIODB_VERSION=1.2.3\nBAZ=qux";
    expect(parseVersionFromEnv(envContent)).toBe("1.2.3");
  });

  it("handles whitespace and quotes in env file", () => {
    expect(parseVersionFromEnv('QURIODB_VERSION="1.2.3"')).toBe("1.2.3");
    expect(parseVersionFromEnv("QURIODB_VERSION='1.2.3'")).toBe("1.2.3");
    expect(parseVersionFromEnv("  QURIODB_VERSION = 1.2.3  ")).toBe("1.2.3");
  });

  it("throws error when QURIODB_VERSION is missing", () => {
    expect(() => parseVersionFromEnv("FOO=bar")).toThrow(
      "Missing QURIODB_VERSION in environment configuration",
    );
  });

  it("throws error on malformed semver 1.2 or prefixed v1.2.3", () => {
    expect(() => validateSemver("1.2")).toThrow("Invalid semantic version: '1.2'");
    expect(() => validateSemver("v1.2.3")).toThrow("Invalid semantic version: 'v1.2.3'");
    expect(() => validateSemver("1.2.3.4")).toThrow("Invalid semantic version: '1.2.3.4'");
    expect(() => validateSemver("latest")).toThrow("Invalid semantic version: 'latest'");
    expect(() => validateSemver("")).toThrow("Invalid semantic version: ''");
  });

  it("validates standard semantic versions", () => {
    expect(validateSemver("0.1.0")).toBe("0.1.0");
    expect(validateSemver("1.2.3")).toBe("1.2.3");
    expect(validateSemver("1.0.0-alpha.1")).toBe("1.0.0-alpha.1");
    expect(validateSemver("2.0.0-rc.2+build.123")).toBe("2.0.0-rc.2+build.123");
  });
});

describe("Version sync and check against fixtures", () => {
  const createFixtureWorkspace = (initialVersion = "0.1.0") => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-version-test-"));

    const desktopPackageJsonRaw = `{
  "name": "desktop",
  "version": "${initialVersion}",
  "description": "Desktop app for QurioDB",
  "main": "main.js",
  "author": "QurioDB Team",
  "private": true,
  "scripts": {
    "dev": "tauri dev",
    "build": "tauri build",
    "tauri": "tauri",
    "test": "vitest run"
  },
  "dependencies": {
  },
  "devDependencies": {
    "@tauri-apps/cli": "^2.1.0",
    "vitest": "^4.0.18"
  }
}
`;

    const tauriConfJsonRaw = `{
  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
  "productName": "QurioDB",
  "version": "${initialVersion}",
  "identifier": "com.quriodb.app",
  "build": {
    "frontendDist": "../../web/dist"
  }
}
`;

    const cargoToml = `[package]
name = "quriodb-desktop"
version = "${initialVersion}"
description = "QurioDB Desktop"

[dependencies]
rand = "0.8"
`;

    const cargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "other-pkg"
version = "0.1.0"

[[package]]
name = "quriodb-desktop"
version = "${initialVersion}"
dependencies = [
 "rand",
]

[[package]]
name = "another-pkg"
version = "0.1.0"
`;

    const rootReadme = `# QurioDB

- [Download Windows Installer (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_x64_en-US.msi)
- [Download Windows Setup (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_x64-setup.exe)
- [Download Linux Package (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_amd64.deb)
- [Download Linux AppImage (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_amd64.AppImage)

QurioDB - v${initialVersion}
`;

    const desktopReadme = `# QurioDB - Desktop Build Guide

_QurioDB Team - v${initialVersion}_
`;

    const sentinelContent = "UNTOUCHED_SENTINEL_DATA_12345";

    fs.mkdirSync(path.join(tempDir, "apps/desktop/src-tauri"), { recursive: true });
    fs.mkdirSync(path.join(tempDir, "unrelated-dir"), { recursive: true });

    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/package.json"),
      desktopPackageJsonRaw,
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/tauri.conf.json"),
      tauriConfJsonRaw,
    );
    fs.writeFileSync(path.join(tempDir, "apps/desktop/src-tauri/Cargo.toml"), cargoToml);
    fs.writeFileSync(path.join(tempDir, "apps/desktop/src-tauri/Cargo.lock"), cargoLock);
    fs.writeFileSync(path.join(tempDir, "README.md"), rootReadme);
    fs.writeFileSync(path.join(tempDir, "apps/desktop/README.md"), desktopReadme);
    fs.writeFileSync(path.join(tempDir, "unrelated-dir/sentinel.txt"), sentinelContent);

    return { tempDir, desktopPackageJsonRaw, tauriConfJsonRaw, sentinelContent };
  };

  it("syncs target version 1.2.3, preserves byte formatting and leaves sentinel untouched", () => {
    const { tempDir: workspace, desktopPackageJsonRaw, sentinelContent } = createFixtureWorkspace("0.1.0");
    const results = syncVersion("1.2.3", workspace);

    expect(results.every((r) => r.updated)).toBe(true);

    const desktopPkgContent = fs.readFileSync(
      path.join(workspace, "apps/desktop/package.json"),
      "utf-8",
    );
    const expectedDesktopPkg = desktopPackageJsonRaw.replace(
      '"version": "0.1.0"',
      '"version": "1.2.3"',
    );
    expect(desktopPkgContent).toBe(expectedDesktopPkg);
    expect(desktopPkgContent).toContain('"dependencies": {\n  }');

    const sentinelActual = fs.readFileSync(
      path.join(workspace, "unrelated-dir/sentinel.txt"),
      "utf-8",
    );
    expect(sentinelActual).toBe(sentinelContent);

    const cargoToml = fs.readFileSync(
      path.join(workspace, "apps/desktop/src-tauri/Cargo.toml"),
      "utf-8",
    );
    expect(cargoToml).toContain('version = "1.2.3"');

    const cargoLock = fs.readFileSync(
      path.join(workspace, "apps/desktop/src-tauri/Cargo.lock"),
      "utf-8",
    );
    expect(cargoLock).toContain('name = "other-pkg"\nversion = "0.1.0"');
    expect(cargoLock).toContain('name = "another-pkg"\nversion = "0.1.0"');
    expect(cargoLock).toContain('name = "quriodb-desktop"\nversion = "1.2.3"');

    const rootReadme = fs.readFileSync(path.join(workspace, "README.md"), "utf-8");
    expect(rootReadme).toContain("Download Windows Installer (v1.2.3)");
    expect(rootReadme).toContain("QurioDB_1.2.3_x64_en-US.msi");
    expect(rootReadme).toContain("QurioDB_1.2.3_x64-setup.exe");
    expect(rootReadme).toContain("QurioDB_1.2.3_amd64.deb");
    expect(rootReadme).toContain("QurioDB_1.2.3_amd64.AppImage");
    expect(rootReadme).toContain("QurioDB - v1.2.3");

    const desktopReadme = fs.readFileSync(
      path.join(workspace, "apps/desktop/README.md"),
      "utf-8",
    );
    expect(desktopReadme).toContain("_QurioDB Team - v1.2.3_");

    fs.rmSync(workspace, { recursive: true, force: true });
  });

  it("checkVersion detects stale files and passes when in sync", () => {
    const { tempDir: workspace } = createFixtureWorkspace("0.1.0");

    const staleResults = checkVersion("1.2.3", workspace);
    const staleFiles = staleResults.filter((r) => !r.inSync).map((r) => r.path);
    expect(staleFiles).toEqual([
      "apps/desktop/package.json",
      "apps/desktop/src-tauri/tauri.conf.json",
      "apps/desktop/src-tauri/Cargo.toml",
      "apps/desktop/src-tauri/Cargo.lock",
      "README.md",
      "apps/desktop/README.md",
    ]);

    syncVersion("1.2.3", workspace);
    const syncedResults = checkVersion("1.2.3", workspace);
    expect(syncedResults.every((r) => r.inSync)).toBe(true);

    fs.rmSync(workspace, { recursive: true, force: true });
  });
});

describe("CLI Boundary and Subprocess Execution", () => {
  const syncScriptPath = path.join(process.cwd(), "scripts/sync-version.ts");

  it("CLI exits 1 with error when .env is missing in fixture root", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-noenv-"));
    const proc = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc.exitCode).toBe(1);
    const stderr = proc.stderr.toString();
    expect(stderr).toContain("Canonical environment file not found");
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("CLI exits 1 when QURIODB_VERSION is malformed (1.2 or v1.2.3)", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-malformed-"));
    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=1.2\n");
    const proc1 = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc1.exitCode).toBe(1);
    expect(proc1.stderr.toString()).toContain("Invalid semantic version: '1.2'");

    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=v1.2.3\n");
    const proc2 = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc2.exitCode).toBe(1);
    expect(proc2.stderr.toString()).toContain("Invalid semantic version: 'v1.2.3'");
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("CLI --check prints every stale path and exits 1 on mismatch", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-stale-"));
    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=2.0.0\n");

    fs.mkdirSync(path.join(tempDir, "apps/desktop/src-tauri"), { recursive: true });
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/package.json"),
      JSON.stringify({ name: "desktop", version: "0.1.0" }, null, 2),
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/tauri.conf.json"),
      JSON.stringify({ productName: "QurioDB", version: "0.1.0" }, null, 2),
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/Cargo.toml"),
      '[package]\nname = "quriodb-desktop"\nversion = "0.1.0"\n',
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/Cargo.lock"),
      '[[package]]\nname = "quriodb-desktop"\nversion = "0.1.0"\n',
    );
    fs.writeFileSync(
      path.join(tempDir, "README.md"),
      "- [Download Windows Installer (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_x64_en-US.msi)\n- [Download Windows Setup (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_x64-setup.exe)\n- [Download Linux Package (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_amd64.deb)\n- [Download Linux AppImage (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_amd64.AppImage)\nQurioDB - v0.1.0\n",
    );
    fs.writeFileSync(path.join(tempDir, "apps/desktop/README.md"), "_QurioDB Team - v0.1.0_\n");

    const checkProc = Bun.spawnSync(["bun", syncScriptPath, "--check"], {
      cwd: tempDir,
    });
    expect(checkProc.exitCode).toBe(1);
    const stderr = checkProc.stderr.toString();
    expect(stderr).toContain("Version mismatch detected! Canonical QURIODB_VERSION=2.0.0");
    expect(stderr).toContain("apps/desktop/package.json");
    expect(stderr).toContain("apps/desktop/src-tauri/tauri.conf.json");
    expect(stderr).toContain("apps/desktop/src-tauri/Cargo.toml");
    expect(stderr).toContain("apps/desktop/src-tauri/Cargo.lock");
    expect(stderr).toContain("README.md");
    expect(stderr).toContain("apps/desktop/README.md");

    const syncProc = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(syncProc.exitCode).toBe(0);

    const checkProcAfter = Bun.spawnSync(["bun", syncScriptPath, "--check"], {
      cwd: tempDir,
    });
    expect(checkProcAfter.exitCode).toBe(0);
    expect(checkProcAfter.stdout.toString()).toContain("All managed targets match QURIODB_VERSION=2.0.0");

    fs.rmSync(tempDir, { recursive: true, force: true });
  });
});

describe("Root package.json desktop scripts validation", () => {
  it("verifies package.json desktop commands include bun run version:sync && prefix", () => {
    const rootPkg = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), "package.json"), "utf-8"),
    );
    const scripts = rootPkg.scripts || {};

    const requiredCommands = [
      "desktop:build",
      "desktop:sidecar:linux",
      "desktop:build:linux",
      "desktop:dev:linux",
      "desktop:dev:windows",
    ];

    for (const cmd of requiredCommands) {
      expect(scripts[cmd]).toBeDefined();
      expect(scripts[cmd].startsWith("bun run version:sync &&")).toBe(true);
    }
  });
});

describe("Desktop release workflow", () => {
  const workflowPath = path.join(process.cwd(), ".github/workflows/release-desktop.yml");

  it("supports platform-selective manual preflight while forcing both platforms for tags", () => {
    const workflow = fs.readFileSync(workflowPath, "utf-8");

    expect(workflow).toMatch(
      /platform:\s*\n\s+description:[\s\S]*?\n\s+required:\s+true\s*\n\s+default:\s+all\s*\n\s+type:\s+choice\s*\n\s+options:\s*\n\s+- all\s*\n\s+- windows\s*\n\s+- linux/,
    );
    expect(workflow).toContain(
      "if: github.event_name == 'push' || inputs.platform == 'all' || inputs.platform == 'windows'",
    );
    expect(workflow).toContain(
      "if: github.event_name == 'push' || inputs.platform == 'all' || inputs.platform == 'linux'",
    );
    expect(workflow).toContain("needs: [build-windows, build-linux]");
    expect(workflow).toContain(
      "if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')",
    );
  });

  it("caches dependencies and Rust targets without caching release outputs", () => {
    const workflow = fs.readFileSync(workflowPath, "utf-8");

    expect(workflow.split("path: ~/.bun/install/cache").length - 1).toBe(2);
    expect(workflow.split("key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}").length - 1).toBe(2);
    expect(workflow.split("cache: pip").length - 1).toBe(2);
    expect(workflow.split("cache-dependency-path: apps/api/requirements.txt").length - 1).toBe(2);
    expect(workflow).toContain("key: windows-msvc");
    expect(workflow).toContain("key: linux-gnu");
    expect(workflow.split("cache-targets: true").length - 1).toBe(2);
    expect(workflow.split("workspaces: apps/desktop/src-tauri -> target").length - 1).toBe(2);
    expect(workflow).not.toMatch(/cache[^\\n]*(node_modules|venv|\\.env|release-assets|api(?:\\.exe)?)/i);
  });

  it("builds both native bundles and releases only after both builds pass", () => {
    expect(fs.existsSync(workflowPath)).toBe(true);
    const workflow = fs.readFileSync(workflowPath, "utf-8");

    expect(workflow).toMatch(/on:\s*\n\s+push:\s*\n\s+tags:\s*\n\s+- v\*\.\*\.\*/);
    expect(workflow).toMatch(/release:[\s\S]*permissions:\s*\n\s+contents: write/);
    expect(workflow).toContain("runs-on: windows-latest");
    expect(workflow).toContain("runs-on: ubuntu-22.04");
    expect(workflow).toContain("build-backend.ps1 -Target msvc");
    expect(workflow).toContain("api-x86_64-pc-windows-msvc.exe");
    expect(workflow).toContain("api-x86_64-unknown-linux-gnu");
    const sidecarBuildIndex = workflow.indexOf("build-backend.ps1 -Target msvc");
    const sidecarCheckIndex = workflow.indexOf("Expected Windows MSVC sidecar was not produced");
    const tauriBuildIndex = workflow.indexOf("bun run tauri build --target x86_64-pc-windows-msvc");
    expect(sidecarBuildIndex).toBeGreaterThanOrEqual(0);
    expect(sidecarCheckIndex).toBeGreaterThan(sidecarBuildIndex);
    expect(tauriBuildIndex).toBeGreaterThan(sidecarCheckIndex);
    expect(workflow).toMatch(/QurioDB_\$\{(?:VERSION|version)\}_x64_en-US\.msi/);
    expect(workflow).toMatch(/QurioDB_\$\{(?:VERSION|version)\}_x64-setup\.exe/);
    expect(workflow).toMatch(/QurioDB_\$\{(?:VERSION|version)\}_amd64\.deb/);
    expect(workflow).toMatch(/QurioDB_\$\{(?:VERSION|version)\}_amd64\.AppImage/);
    expect(workflow).toContain("needs: [build-windows, build-linux]");
    expect(workflow).toContain('gh release create "$GITHUB_REF_NAME"');
    expect(workflow).toContain('gh release view "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY"');
    expect(workflow).toContain("Release already exists; refusing to modify or overwrite");
    expect(workflow).toContain('git ls-remote "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" "refs/tags/$GITHUB_REF_NAME"');
    expect(workflow).toContain('remote_sha="$(git ls-remote');
    expect(workflow).toContain('remote_sha" != "$GITHUB_SHA"');
    expect(workflow).toContain('--verify-tag');
    expect(workflow).toContain('title "release-v$VERSION"');
  });

  it("supports safe manual preflight and cleans up frozen sidecars before packaging", () => {
    const workflow = fs.readFileSync(workflowPath, "utf-8");

    expect(workflow).toContain("workflow_dispatch:");
    expect(workflow).toMatch(/workflow_dispatch:[\s\S]*version:[\s\S]*required:\s*true/);
    expect(workflow).toContain("id: version");
    expect(workflow).not.toContain("apps/api/.env");
    expect(workflow).toContain("if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')");

    const windowsSmokeIndex = workflow.indexOf("Smoke-test Windows FastAPI sidecar");
    const windowsTauriIndex = workflow.indexOf("bun run tauri build --target x86_64-pc-windows-msvc");
    const linuxSmokeIndex = workflow.indexOf("Smoke-test Linux FastAPI sidecar");
    const linuxTauriIndex = workflow.indexOf("bun run tauri build --target x86_64-unknown-linux-gnu");

    expect(windowsSmokeIndex).toBeGreaterThanOrEqual(0);
    expect(windowsSmokeIndex).toBeLessThan(windowsTauriIndex);
    expect(workflow.slice(windowsSmokeIndex, windowsTauriIndex)).toContain("/health");
    expect(workflow.slice(windowsSmokeIndex, windowsTauriIndex)).toContain("taskkill");
    expect(linuxSmokeIndex).toBeGreaterThanOrEqual(0);
    expect(linuxSmokeIndex).toBeLessThan(linuxTauriIndex);
    expect(workflow.slice(linuxSmokeIndex, linuxTauriIndex)).toContain("/health");
    expect(workflow.slice(linuxSmokeIndex, linuxTauriIndex)).toContain("trap cleanup EXIT");
  });

  it("uses the authenticated desktop readiness contract for the Windows smoke test", () => {
    const workflow = fs.readFileSync(workflowPath, "utf-8");
    const smokeStart = workflow.indexOf("Smoke-test Windows FastAPI sidecar");
    const buildStart = workflow.indexOf("Build Windows MSI and NSIS bundles");
    const smoke = workflow.slice(smokeStart, buildStart);

    expect(smoke).toMatch(/\$env:QURIODB_STARTUP_NONCE\s*=\s*\[guid\]::NewGuid\(\)\.ToString\('N'\)/);
    expect(smoke).toContain("$env:QURIODB_DESKTOP_PARENT_PID = $PID");
    expect(smoke).toContain("-RedirectStandardOutput $stdoutLog");
    expect(smoke).toContain("-RedirectStandardError $stderrLog");
    expect(smoke).toContain("$stdoutLog = Join-Path $env:RUNNER_TEMP");
    expect(smoke).toContain("$stderrLog = Join-Path $env:RUNNER_TEMP");
    expect(smoke).toMatch(/function Write-SidecarLogs\s*\{[\s\S]*?param\(\s*\[string\]\$stdoutPath,\s*\[string\]\$stderrPath\s*\)[\s\S]*?Get-Content -LiteralPath \$stdoutPath[\s\S]*?Get-Content -LiteralPath \$stderrPath[\s\S]*?\}/);
    expect(smoke).toContain("Write-SidecarLogs -stdoutPath $stdoutLog -stderrPath $stderrLog");
    const logCallIndex = smoke.indexOf("Write-SidecarLogs -stdoutPath $stdoutLog -stderrPath $stderrLog");
    const throwIndex = smoke.indexOf("throw\n", logCallIndex);
    expect(logCallIndex).toBeGreaterThanOrEqual(0);
    expect(throwIndex).toBeGreaterThan(logCallIndex);
    expect(smoke).toContain("/api/desktop/health");
    expect(smoke).toContain('X-QurioDB-Startup-Nonce');
    expect(smoke).toContain("$body.status -ne 'ok'");
    expect(smoke).toContain("$body.service -ne 'quriodb-desktop'");
    expect(smoke).toContain("$attempt -lt 180");
    expect(smoke).toContain("Start-Sleep -Milliseconds 500");
    expect(smoke).toContain("Get-Content -LiteralPath $stdoutPath");
    expect(smoke).toContain("Get-Content -LiteralPath $stderrPath");
    expect(smoke).toContain("catch {");
    expect(smoke).toContain("finally {");
    expect(smoke).toContain("taskkill.exe /F /T /PID");
    expect(smoke).toContain("Remove-Item Env:QURIODB_DESKTOP_PORT");
    expect(smoke).toContain("Remove-Item Env:QURIODB_STARTUP_NONCE");
    expect(smoke).toContain("Remove-Item Env:QURIODB_DESKTOP_PARENT_PID");
  });

  it("requires exact stable versions for tag releases and manual preflight", () => {
    const workflow = fs.readFileSync(workflowPath, "utf-8");
    const stableTag = /^v\d+\.\d+\.\d+$/;
    const stableInput = /^\d+\.\d+\.\d+$/;

    expect(stableTag.test("v0.1.3")).toBe(true);
    expect(stableTag.test("v0.1.3-rc.1")).toBe(false);
    expect(stableInput.test("0.1.3")).toBe(true);
    expect(stableInput.test("0.1.3-rc.1")).toBe(false);
    expect(workflow).toContain("^v[0-9]+\\.[0-9]+\\.[0-9]+$");
    expect(workflow).toContain("^[0-9]+\\.[0-9]+\\.[0-9]+$");
  });
});

describe("Windows sidecar build script", () => {
  it("anchors the destination to the repository and restores the caller location", () => {
    const script = fs.readFileSync(path.join(process.cwd(), "build-backend.ps1"), "utf-8");

    expect(script).toContain("$REPO_ROOT = (Resolve-Path -LiteralPath $PSScriptRoot).Path");
    expect(script).toContain('$DEST_DIR = Join-Path $REPO_ROOT "apps/desktop/src-tauri/bin"');
    expect(script).toContain("Push-Location -LiteralPath $API_DIR");
    expect(script).toContain("Pop-Location");
    expect(script).not.toContain('"../../$DEST_DIR"');
  });
});
